import { Dimensions, Platform, StyleSheet } from 'react-native';

const { width: screenWidth } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1a1a1a',
  },
  flex: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 40,
  },
  
  // Sticky Header
  stickyHeader: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: Platform.OS === 'ios' ? 100 : 80,
    backgroundColor: 'rgba(26, 26, 26, 0.98)',
    zIndex: 1000,
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: Platform.OS === 'ios' ? 45 : 25,
    borderBottomWidth: 2,
    borderBottomColor: 'rgba(255, 107, 107, 0.4)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 10,
  },
  stickyLogoText: {
    fontSize: 32,
    fontWeight: 'bold',
    letterSpacing: -0.5,
  },
  stickyLogoMain: {
    color: '#fff',
  },
  stickyLogoOrange: {
    color: '#FF6B6B',
  },
  stickyLogoDot: {
    color: '#FF6B6B',
  },
  
  // Header
  headerContainer: {
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'ios' ? 20 : 40,
    paddingBottom: 10,
    alignItems: 'center',
  },
  headerTop: {
    position: 'absolute',
    top: 35,
    left: 20,
    zIndex: 10,
  },
  logoContainer: {
    alignItems: 'center',
    marginBottom: 0,
  },
  logoTextContainer: {
    alignItems: 'center',
    marginBottom: 12,
    position: 'relative',
  },
  logoText: {
    fontSize: 48,
    fontWeight: 'bold',
    letterSpacing: -1,
  },
  logoMain: {
    color: '#fff',
  },
  logoOrange: {
    color: '#FF6B6B',
  },
  logoDot: {
    color: '#FF6B6B',
  },
  tagline: {
    fontSize: 18,
    color: '#888',
    textAlign: 'center',
    fontWeight: '300',
    letterSpacing: 0.5,
    position: 'relative',
  },
  
  // Burger Menu
  burgerButtonMain: {
    padding: 12,
    justifyContent: 'center',
    alignItems: 'center',
    width: 48,
    height: 48,
  },
  burgerLineMain: {
    width: 26,
    height: 3,
    backgroundColor: '#FF6B6B',
    marginVertical: 3,
    borderRadius: 2,
  },
  
  // Menu Panel
  menuOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    zIndex: 1000,
  },
  menuPanel: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    width: 300,
    backgroundColor: 'rgba(26, 26, 26, 0.98)',
    zIndex: 1001,
    borderRightWidth: 1,
    borderRightColor: 'rgba(255, 107, 107, 0.3)',
    paddingTop: Platform.OS === 'ios' ? 60 : 40,
  },
  menuHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: Platform.OS === 'ios' ? 45 : 25,
    paddingBottom: 24,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 107, 107, 0.2)',
    backgroundColor: 'rgba(255, 107, 107, 0.05)',
  },
  menuTitle: {
    fontSize: 32,
    fontWeight: 'bold',
    letterSpacing: -0.5,
  },
  menuTitleMain: {
    color: '#fff',
    textShadowColor: 'rgba(255, 255, 255, 0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  menuTitleOrange: {
    color: '#FF6B6B',
    textShadowColor: 'rgba(255, 107, 107, 0.5)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  closeButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255, 107, 107, 0.15)',
    borderWidth: 1,
    borderColor: 'rgba(255, 107, 107, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#FF6B6B',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  closeButtonText: {
    color: '#FF6B6B',
    fontSize: 22,
    fontWeight: 'bold',
    lineHeight: 22,
  },
  menuItems: {
    flex: 1,
    paddingTop: 16,
    paddingHorizontal: 8,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    marginVertical: 2,
    marginHorizontal: 8,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
    borderWidth: 1,
    borderColor: 'transparent',
  },
  menuItemPressed: {
    backgroundColor: 'rgba(255, 107, 107, 0.1)',
    borderColor: 'rgba(255, 107, 107, 0.2)',
    shadowColor: '#FF6B6B',
    shadowOpacity: 0.2,
    elevation: 3,
  },
  menuItemIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255, 107, 107, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(255, 107, 107, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
    shadowColor: '#FF6B6B',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  menuItemIconText: {
    fontSize: 20,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  menuItemText: {
    color: '#fff',
    fontSize: 17,
    fontWeight: '600',
    flex: 1,
    letterSpacing: 0.3,
    textShadowColor: 'rgba(255, 255, 255, 0.1)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 1,
  },
  menuItemChevron: {
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  menuItemChevronText: {
    color: 'rgba(255, 107, 107, 0.6)',
    fontSize: 18,
    fontWeight: 'bold',
  },
  menuFooter: {
    paddingHorizontal: 24,
    paddingVertical: 24,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 107, 107, 0.2)',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 107, 107, 0.03)',
  },
  menuFooterText: {
    color: '#FF6B6B',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.5,
    textShadowColor: 'rgba(255, 107, 107, 0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  menuFooterSubtext: {
    color: '#888',
    fontSize: 11,
    marginTop: 4,
    fontWeight: '500',
    letterSpacing: 0.3,
    fontStyle: 'italic',
  },
  
  // Welcome Section
  welcomeSection: {
    paddingHorizontal: 20,
    paddingBottom: 20,
    paddingTop: 5,
  },
  
  // Training Stats
  trainingStatsContainer: {
    alignItems: 'center',
    marginBottom: 30,
    marginTop: 15,
  },
  trainingStatsContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    position: 'relative',
    zIndex: 2,
  },
  lightningIcon: {
    width: 16,
    height: 20,
    position: 'relative',
  },
  lightningBolt: {
    position: 'absolute',
    top: 0,
    left: 6,
    width: 0,
    height: 0,
    borderLeftWidth: 4,
    borderRightWidth: 6,
    borderTopWidth: 12,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderTopColor: '#FF6B6B',
  },
  lightningTail: {
    position: 'absolute',
    bottom: 0,
    left: 2,
    width: 0,
    height: 0,
    borderLeftWidth: 6,
    borderRightWidth: 4,
    borderBottomWidth: 8,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: '#FF6B6B',
  },
  trainingStatsText: {
    color: '#888',
    fontSize: 14,
    fontWeight: '500',
    letterSpacing: 0.3,
  },
  trainingStatsGlow: {
    position: 'absolute',
    top: -2,
    left: -10,
    right: -10,
    bottom: -2,
    backgroundColor: 'transparent',
    shadowColor: '#FF6B6B',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    borderRadius: 12,
  },
  
  // Message Animation
  messageAnimation: {
    height: 280,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 40,
    position: 'relative',
  },
  messageBubble: {
    backgroundColor: '#333',
    paddingHorizontal: 20,
    paddingVertical: 15,
    borderRadius: 20,
    borderTopLeftRadius: 5,
    maxWidth: screenWidth * 0.8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    position: 'relative',
    overflow: 'hidden',
  },
  surfaceText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '500',
  },
  scanningLine: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: 2,
    backgroundColor: '#FF6B6B',
    shadowColor: '#FF6B6B',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 8,
    elevation: 5,
  },
  hiddenIntentBubble: {
    position: 'absolute',
    top: 85,
    backgroundColor: '#FF6B6B',
    paddingHorizontal: 24,
    paddingVertical: 18,
    borderRadius: 20,
    maxWidth: screenWidth * 0.88,
    minWidth: screenWidth * 0.75,
    shadowColor: '#FF6B6B',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.6,
    shadowRadius: 16,
    elevation: 15,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  hiddenText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
    letterSpacing: 0.3,
    lineHeight: 22,
  },
  intentArrow: {
    position: 'absolute',
    top: -10,
    left: '50%',
    marginLeft: -10,
    width: 0,
    height: 0,
    borderLeftWidth: 10,
    borderRightWidth: 10,
    borderBottomWidth: 10,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: '#FF6B6B',
  },
  analysisLayer: {
    position: 'absolute',
    top: 160,
    backgroundColor: '#0a0a0a',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderRadius: 16,
    maxWidth: screenWidth * 0.9,
    minWidth: screenWidth * 0.8,
    borderWidth: 1,
    borderColor: '#333',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.5,
    shadowRadius: 16,
    elevation: 16,
  },
  analysisHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    gap: 10,
  },
  analysisIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#FF6B6B',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#FF6B6B',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 4,
  },
  analysisIconText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: 'bold',
  },
  analysisTitle: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
    flex: 1,
  },
  manipulationBadge: {
    backgroundColor: 'rgba(255, 0, 0, 0.2)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(255, 0, 0, 0.3)',
  },
  manipulationType: {
    color: '#ff4444',
    fontSize: 9,
    fontWeight: '600',
  },
  analysisText: {
    color: '#ccc',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '500',
  },
  cursor: {
    color: '#FF6B6B',
    fontSize: 13,
    fontWeight: 'bold',
    opacity: 0.8,
  },
  
  // Action Buttons
  actionButtons: {
    gap: 15,
  },
  uploadButton: {
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#FF6B6B',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 10,
  },
  uploadGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    paddingHorizontal: 24,
    gap: 12,
  },
  cameraIcon: {
    width: 24,
    height: 20,
    position: 'relative',
  },
  cameraBody: {
    width: 24,
    height: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 4,
    position: 'absolute',
    bottom: 0,
  },
  cameraLens: {
    width: 12,
    height: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    borderRadius: 6,
    position: 'absolute',
    bottom: 2,
    left: 6,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.9)',
  },
  cameraFlash: {
    width: 4,
    height: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 2,
    position: 'absolute',
    top: 0,
    left: 4,
  },
  uploadText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  manualButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  manualButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  
  // Text Input
  textInputContainer: {
    marginTop: 15,
    gap: 12,
  },
  textInput: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 12,
    padding: 16,
    color: '#fff',
    fontSize: 16,
    minHeight: 100,
    textAlignVertical: 'top',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  analyzeButton: {
    borderRadius: 12,
    overflow: 'hidden',
  },
  analyzeButtonGradient: {
    paddingVertical: 14,
    paddingHorizontal: 20,
    alignItems: 'center',
  },
  analyzeButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  
  // Scanning Animation
  scanningContainer: {
    alignItems: 'center',
    marginVertical: 15,
    gap: 15,
  },
  scanningImageContainer: {
    position: 'relative',
    borderRadius: 15,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 12,
  },
  scanningImage: {
    width: screenWidth * 0.8,
    height: undefined,
    aspectRatio: 1,
    resizeMode: 'cover',
  },
  scanLineOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
  },
  scanLine: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: 3,
    backgroundColor: '#FF6B6B',
    shadowColor: '#FF6B6B',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 10,
    elevation: 5,
  },
  scanStatus: {
    alignItems: 'center',
    gap: 4,
  },
  scanStatusText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  scanStatusSubtext: {
    color: '#888',
    fontSize: 14,
  },
  
  // Image Container
  imageContainer: {
    paddingHorizontal: 20,
    marginBottom: 15,
  },
  imageCard: {
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 10,
  },
  fullImage: {
    width: '100%',
    height: undefined,
    aspectRatio: 1,
    resizeMode: 'contain',
  },
  
  // Divider
  dividerContainer: {
    marginVertical: 20,
    alignItems: 'center',
    gap: 12,
  },
  dividerGradient: {
    height: 2,
    width: '100%',
  },
  dividerTextContainer: {
    alignItems: 'center',
    gap: 4,
  },
  dividerText: {
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  dividerSub: {
    color: '#fff',
  },
  dividerTextOrange: {
    color: '#FF6B6B',
  },
  dividerSubtext: {
    color: '#888',
    fontSize: 13,
    textAlign: 'center',
  },
  
  // Analysis Container
  analysisContainer: {
    paddingHorizontal: 20,
    gap: 15,
  },
  
  // Selected Messages Card
  selectedMessagesCard: {
    backgroundColor: '#0f0f0f',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#333',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 10,
    marginBottom: 10,
  },
  selectedMessagesHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
  },
  messageIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 107, 107, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 107, 107, 0.3)',
  },
  messageIconText: {
    fontSize: 20,
  },
  selectedMessagesTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  selectedMessagesBody: {
    padding: 16,
    gap: 12,
  },
  selectedMessageBubble: {
    backgroundColor: 'rgba(255, 107, 107, 0.1)',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 12,
    borderLeftWidth: 3,
    borderLeftColor: '#FF6B6B',
    marginVertical: 2,
  },
  selectedMessageText: {
    color: '#fff',
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '500',
    fontStyle: 'italic',
  },
  
  // Hidden Intent Card (New Style)
  hiddenIntentCard: {
    backgroundColor: '#0a0a0a',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#333',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.5,
    shadowRadius: 16,
    elevation: 16,
    marginBottom: 15,
  },
  intentCard: {
    backgroundColor: '#0f0f0f',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#333',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 10,
    marginTop: -5,
  },
  intentHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
  },
  psychologyIcon: {
    width: 40,
    height: 40,
    position: 'relative',
    marginRight: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  eyeIcon: {
    width: 32,
    height: 20,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#FF6B6B',
    position: 'absolute',
  },
  eyePupil: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#FF6B6B',
    position: 'absolute',
  },
  intentTitleContainer: {
    flex: 1,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  intentTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  typeBadge: {
    backgroundColor: 'rgba(255, 0, 0, 0.2)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(255, 0, 0, 0.3)',
  },
  typeText: {
    color: '#ff4444',
    fontSize: 11,
    fontWeight: '600',
  },
  confidenceMeter: {
    width: '60%', // Made smaller - was 100%
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  confidenceBar: {
    height: 3, // Made smaller - was 4
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 2,
    overflow: 'hidden',
  },
  confidenceFill: {
    height: '100%',
    borderRadius: 2,
  },
  confidenceText: {
    color: '#FF6B6B',
    fontSize: 10,
    fontWeight: '600',
    minWidth: 30, // Ensures consistent spacing
  },
  intentBody: {
    padding: 16,
  },
  intentText: {
    color: '#fff',
    fontSize: 15,
    lineHeight: 22,
    fontWeight: '500',
  },
  
  // Response Card
  responseCard: {
    backgroundColor: '#0f0f0f',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#333',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 10,
  },
  responseHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
  },
  shieldIcon: {
    width: 40,
    height: 40,
    position: 'relative',
    marginRight: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  shieldOuter: {
    width: 32,
    height: 36,
    backgroundColor: '#333',
    borderRadius: 16,
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
    position: 'absolute',
  },
  shieldInner: {
    width: 24,
    height: 28,
    backgroundColor: '#FFD700',
    borderRadius: 12,
    borderBottomLeftRadius: 6,
    borderBottomRightRadius: 6,
    position: 'absolute',
  },
  shieldCenter: {
    width: 8,
    height: 8,
    backgroundColor: '#333',
    borderRadius: 4,
    position: 'absolute',
  },
  responseTitleContainer: {
    flex: 1,
  },
  responseTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 2,
  },
  responseSubtitle: {
    color: '#888',
    fontSize: 12,
    fontWeight: '500',
  },
  responseBody: {
    padding: 16,
    gap: 12,
  },
  responseText: {
    color: '#fff',
    fontSize: 15,
    lineHeight: 22,
    fontWeight: '500',
    marginBottom: 4,
  },
  copyButton: {
    backgroundColor: 'rgba(255, 107, 107, 0.2)',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 107, 107, 0.3)',
    alignSelf: 'flex-start',
  },
  copyButtonText: {
    color: '#FF6B6B',
    fontSize: 12,
    fontWeight: '600',
  },
  
  // New Analysis Button
  newAnalysisButtonContainer: {
    paddingBottom: 20,
  },
  newAnalysisButton: {
    position: 'relative',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255, 107, 107, 0.3)',
    overflow: 'hidden',
    shadowColor: '#FF6B6B',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
  },
  newAnalysisGlow: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255, 107, 107, 0.1)',
    opacity: 0.5,
  },
  newAnalysisContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 20,
    gap: 10,
  },
  resetIcon: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'rgba(255, 107, 107, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  resetIconInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#FF6B6B',
  },
  resetText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
});

export default styles;